apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ash-worker
  namespace: ayon
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['create', 'list', 'delete']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ash-worker-binding
  namespace: ayon
subjects:
  - kind: ServiceAccount
    name: ayon-worker
roleRef:
  kind: Role
  name: ash-worker
  apiGroup: rbac.authorization.k8s.io